name: 'juzerzarif-org/action-milton-auth'

description: Mints a new GitHub auth token for milton-bot to be used in a workflow

inputs:
  milton-secrets:
    description: Secrets payload for milton-bot. This is defined at org level. Most cases you just wanna pass secrets.MILTON_SECRETS
    required: true
  permissions:
    description: Permissions to be granted to this token
    required: false

outputs:
  token:
    description: A GitHub auth token

runs:
  using: node16
  main: dist/index.js
  # post: dist/cleanup.js

branding:
  icon: key
  color: blue
