name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: ./
        id: milton-auth
        with:
          milton-secrets: ${{ secrets.MILTON_SECRETS }}
          permissions: |
            contents:read
            metadata:read

      - name: Test git
        run: git ls-remote --heads ssh://git@github.com/juzerzarif-org/package-a.git
